mehr-schulferien-de/www.mehr-schulferien.de

phoenix/lib/mehr_schulferien_web/templates/bridge_day/federal_state/index.html.eex, phoenix/lib/mehr_schulferien_web/templates/bridge_day/federal_state/show.html.eex, phoenix/lib/mehr_schulferien_web/templates/bridge_day/shared/_landing_calendar.html.eex, phoenix/lib/mehr_schulferien_web/templates/bridge_day/shared/_month.html.eex
Update anchor a href to Kalenderansicht (issue #29 )
=> Update anchor a href to Kalenderansicht 

phoenix/lib/mehr_schulferien_web/templates/bridge_day/shared/_landing_calendar.html.eex
=> bugs fix misplaced free days

phoenix/lib/mehr_schulferien_web/controllers/bridge_day/federal_state_controller.ex, phoenix/lib/mehr_schulferien_web/templates/bridge_day/federal_state/index.html.eex, phoenix/lib/mehr_schulferien_web/templates/bridge_day/federal_state/show.html.eex, phoenix/lib/mehr_schulferien_web/templates/bridge_day/shared/_landing_calendar.html.eex
=> fix two column/card for medium size screen

phoenix/lib/mehr_schulferien_web/controllers/bridge_day/federal_state_controller.ex, phoenix/lib/mehr_schulferien_web/templates/bridge_day/federal_state/index.html.eex, phoenix/lib/mehr_schulferien_web/templates/bridge_day/shared/_landing_event_schema.html.eex
=> Schema bridge days teaser

lib/mehr_schulferien/calendars.ex, priv/repo/seeds-public-holidays.exs, priv/repo/seeds-vacations.exs, test/mehr_schulferien/calendars_test.exs, test/mehr_schulferien/maps_test.exs, test/mehr_schulferien_web/controllers/holiday_or_vacation_type_controller_test.exs, test/mehr_schulferien_web/controllers/location_controller_test.exs, test/mehr_schulferien_web/controllers/period_controller_test.exs, test/mehr_schulferien_web/controllers/religion_controller_test.exs, test/mehr_schulferien_web/controllers/zip_code_controller_test.exs, test/mehr_schulferien_web/controllers/zip_code_mapping_controller_test.exs, test/support/conn_case.ex, test/support/factory.ex
Updated controller tests - so all the tests are passing now.
=> Controller tests

lib/ecto_slugs/location_name.ex, lib/mehr_schulferien/display/federal_state.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/templates/federal_state/index.html.eex, test/mehr_schulferien/location_slugs_test.exs
Refactored this module so that it is a little easier to read and added tests. See tests for more details about how the slugs are formatted.
=> Refactored the LocationName slug-generating module

lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, test/mehr_schulferien/display_test.exs, test/mehr_schulferien_web/controllers/federal_state_controller_test.exs
Addresses #49 - rendering the data automatically.
=> Updated the federal_state_controller to render data automatically

lib/mehr_schulferien/calendars/period.ex, lib/mehr_schulferien/display.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/views/view_helpers.ex, test/mehr_schulferien/calendars_test.exs, test/mehr_schulferien/display_test.exs, test/mehr_schulferien_web/views/view_helpers_test.exs
This PR:
* updates view_helpers functions
* adds view_helpers tests
* starts work on #58 - fixing it for the 12 months table
=> Federal state display

lib/mehr_schulferien/display.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, test/mehr_schulferien/display_test.exs
Addresses #57, but we still need to add a further check that all the periods align with the headers.
=> Updated 3-year periods table

lib/mehr_schulferien/display.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar.html.eex, lib/mehr_schulferien_web/views/view_helpers.ex, priv/repo/seeds-public-holidays.exs, test/mehr_schulferien_web/views/view_helpers_test.exs
Related to #63, updated vacation calendar to properly display periods depending on display_priority and to show public holidays in each month's summary.
=> Public hol calendar

lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/partial/_one_year_periods_table.html.eex, lib/mehr_schulferien_web/templates/partial/_three_year_periods_table.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar_summary.html.eex, lib/mehr_schulferien_web/views/view_helpers.ex
Fixes the html bug in the calendar, adds class="active" to the current year row in the 3-year table and adds links from the tables to the calendar.
I think the internal links can be made a little simpler - we can discuss that later.
=> Fixes #78, #80 and #81

lib/mehr_schulferien/maps.ex, lib/mehr_schulferien_web/controllers/county_controller.ex, lib/mehr_schulferien_web/templates/county/show.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar_summary.html.eex, lib/mehr_schulferien_web/views/county_view.ex, test/mehr_schulferien/display_test.exs, test/mehr_schulferien/maps_test.exs, test/mehr_schulferien_web/controllers/federal_state_controller_test.exs, test/mehr_schulferien_web/controllers/location_controller_test.exs, test/mehr_schulferien_web/controllers/page_controller_test.exs, test/mehr_schulferien_web/controllers/period_controller_test.exs, test/mehr_schulferien_web/controllers/zip_code_mapping_controller_test.exs, test/mehr_schulferien_web/views/county_view_test.exs, test/support/factory.ex
=> List cities

lib/mehr_schulferien_web/templates/city/show.html.eex, lib/mehr_schulferien_web/templates/county/show.html.eex
This fixes the bug when displaying a county or city.
=> Fixed no assigns for current_year bug in calendar for county

lib/mehr_schulferien/locations.ex, lib/mehr_schulferien/maps.ex, lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/controllers/city_controller.ex, lib/mehr_schulferien_web/controllers/county_controller.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/router.ex, test/mehr_schulferien/locations_test.exs, test/mehr_schulferien/maps_test.exs, test/mehr_schulferien/periods_test.exs
Moved the functions in the Display module to the Locations (for location-related functions) and Periods modules.
=> Reorganized the functions in the Display module by creating Locations and Periods modules

lib/mehr_schulferien/calendars/date_helpers.ex, lib/mehr_schulferien/locations.ex, lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/controllers/city_controller.ex, lib/mehr_schulferien_web/controllers/county_controller.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/controllers/page_controller.ex, lib/mehr_schulferien_web/templates/page/index.html.eex, lib/mehr_schulferien_web/templates/partial/_current_calendar.html.eex, test/mehr_schulferien/calendars_test.exs, test/mehr_schulferien/locations_test.exs, test/mehr_schulferien/maps_test.exs, test/mehr_schulferien/periods_test.exs, test/mehr_schulferien_web/controllers/page_controller_test.exs, test/support/factory.ex
=> Started work on partial calendar for root page

.pre-commit-config.yaml, CONTRIBUTING.md, README.md
Fixes #112.
This PR includes a pre-commit hook to prevent anyone from directly committing changes to the `v5` branch.
=> Added pre-commit and a CONTRIBUTING guide

lib/mehr_schulferien_web/controllers/controller_helpers.ex, lib/mehr_schulferien_web/templates/federal_state/county_show.html.eex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar_summary.html.eex, lib/mehr_schulferien_web/views/view_helpers.ex, test/mehr_schulferien_web/views/view_helpers_test.exs
=> Update vacation calendar

lib/mehr_schulferien/calendars.ex, lib/mehr_schulferien/calendars/holiday_or_vacation_type.ex, lib/mehr_schulferien/calendars/religion.ex, lib/mehr_schulferien/locations.ex, lib/mehr_schulferien/maps.ex, lib/mehr_schulferien/maps/address.ex, lib/mehr_schulferien/maps/location.ex, lib/mehr_schulferien/maps/zip_code.ex, lib/mehr_schulferien/maps/zip_code_mapping.ex, lib/mehr_schulferien_web/controllers/city_controller.ex, lib/mehr_schulferien_web/controllers/location_controller.ex, lib/mehr_schulferien_web/controllers/school_controller.ex, priv/repo/migrations/20200124142800_create_locations.exs, priv/repo/migrations/20200126102003_create_zip_codes.exs, priv/repo/migrations/20200126102551_create_zip_code_mappings.exs, priv/repo/migrations/20200129143107_create_holiday_or_vacation_types.exs, priv/repo/migrations/20200129151006_create_periods.exs, priv/repo/migrations/20200312060652_create_addresses.exs, test/mehr_schulferien/location_slugs_test.exs, test/mehr_schulferien/locations_test.exs, test/mehr_schulferien/maps_test.exs, test/mehr_schulferien/periods_test.exs, test/mehr_schulferien_web/controllers/location_controller_test.exs, test/support/factory.ex
Added addresses table and reorganized the Maps and Locations context modules.
=> Moved Maps.Location query functions to Locations context module and added addresses table

lib/mehr_schulferien/locations.ex, lib/mehr_schulferien_web/controllers/city_controller.ex, lib/mehr_schulferien_web/templates/city/show.html.eex, priv/repo/reset-db.sh
Fixes #122.
This also add `set -e` to the `reset-db.sh` script so that it exits if there is an error in any of the commands.
=> Added list of schools to city show page

CONTRIBUTING.md, lib/mehr_schulferien/maps/zip_code_mapping.ex, priv/repo/seeds.exs
Updated the CONTRIBUTING guide in line with the recent changes to the repository - the `v5` branch has been moved to `master`.
=> Small update to CONTRIBUTING guide

lib/mehr_schulferien_web/templates/city/show.html.eex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/school/show.html.eex, priv/repo/seeds.exs, test/mehr_schulferien_web/controllers/federal_state_controller_test.exs
=> Added schema.org events to federal_state, city and school pages

CONTRIBUTING.md
First PR, following the contribution guide
=> Fix wording

.pre-commit-config.yaml, CONTRIBUTING.md, mix.exs
=> Updated CONTRIBUTING guide

lib/mehr_schulferien_web/controllers/api/v2/location_controller.ex, lib/mehr_schulferien_web/router.ex, lib/mehr_schulferien_web/views/api/v2/location_view.ex
=> Create /locations API endpoint

CONTRIBUTING.md, lib/mehr_schulferien/locations.ex, lib/mehr_schulferien_web/controllers/page_controller.ex, lib/mehr_schulferien_web/templates/city/meta.show.html.eex, lib/mehr_schulferien_web/templates/federal_state/meta.show.html.eex, lib/mehr_schulferien_web/templates/layout/app.html.eex, lib/mehr_schulferien_web/templates/layout/meta.html.eex, lib/mehr_schulferien_web/templates/page/meta.index.html.eex, lib/mehr_schulferien_web/templates/school/meta.show.html.eex, lib/mehr_schulferien_web/views/city_view.ex, lib/mehr_schulferien_web/views/page_view.ex, test/mehr_schulferien_web/controllers/city_controller_test.exs, test/mehr_schulferien_web/controllers/federal_state_controller_test.exs, test/mehr_schulferien_web/controllers/page_controller_test.exs, test/mehr_schulferien_web/controllers/school_controller_test.exs
=> Added dynamic meta tags for root, federal_state, city and school show pages

lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/controllers/api/v2/period_controller.ex, lib/mehr_schulferien_web/router.ex, lib/mehr_schulferien_web/views/api/v2/period_view.ex
=> Create /periods endpoint

lib/mehr_schulferien/locations.ex, lib/mehr_schulferien_web/controllers/city_controller.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/controllers/school_controller.ex, lib/mehr_schulferien_web/router.ex, lib/mehr_schulferien_web/templates/city/form.html.eex, lib/mehr_schulferien_web/templates/city/new.html.eex, lib/mehr_schulferien_web/templates/federal_state/new.html.eex, lib/mehr_schulferien_web/templates/school/form.html.eex, lib/mehr_schulferien_web/templates/school/new.html.eex, test/mehr_schulferien_web/controllers/city_controller_test.exs, test/mehr_schulferien_web/controllers/federal_state_controller_test.exs, test/mehr_schulferien_web/controllers/school_controller_test.exs
Part of #124. Users can now add the quarantine period for cities and schools.
=> Updated ability for users to add quarantine period to cities and schools

lib/mehr_schulferien_web/templates/city/show.html.eex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/school/show.html.eex
Updated schema events data to use the `colloquial` value if present and to update school address information.
=> Fixes #187 and #188

lib/mehr_schulferien_web/templates/page/index.html.eex, lib/mehr_schulferien_web/templates/partial/_current_calendar.html.eex, test/support/factory.ex
Cleans up the links on the root page calendar.
=> Fixes #132

lib/mehr_schulferien_web/templates/layout/app.html.eex, lib/mehr_schulferien_web/views/view_helpers.ex
=> Add version number to the footer of each page

lib/mehr_schulferien_web/templates/school/show.html.eex, lib/mehr_schulferien_web/views/school_view.ex, test/mehr_schulferien_web/views/school_view_test.exs
Fixes #189
Closes #225
This is how the view would look:
=> Display school url and email

lib/mehr_schulferien_web/templates/layout/app.html.eex
=> Vertically allign table to text

lib/mehr_schulferien_web/templates/school/show.html.eex, lib/mehr_schulferien_web/views/school_view.ex, test/mehr_schulferien_web/views/school_view_test.exs
=> Fix links and emails to schools

lib/mehr_schulferien/locations.ex, lib/mehr_schulferien_web/controllers/old_routes/city_controller.ex
Improves the redirects from old city routes.
=> Fixes #236

lib/mehr_schulferien_web/templates/partial/_vacation_calendar_summary.html.eex
=> Fix label colour

lib/mehr_schulferien/calendars.ex, lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/controllers/controller_helpers.ex, lib/mehr_schulferien_web/controllers/old_routes/city_controller.ex, lib/mehr_schulferien_web/templates/city/show.html.eex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/partial/_one_year_periods_table.html.eex, lib/mehr_schulferien_web/templates/partial/_three_year_periods_table.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar.html.eex, lib/mehr_schulferien_web/templates/school/show.html.eex, test/mehr_schulferien/calendars_test.exs, test/mehr_schulferien/periods_test.exs
=> Fixed bug in vacation calendar - not showing certain holiday periods

test/mehr_schulferien/periods_test.exs, test/mehr_schulferien_web/controllers/city_controller_test.exs, test/mehr_schulferien_web/controllers/federal_state_controller_test.exs, test/mehr_schulferien_web/controllers/page_controller_test.exs, test/mehr_schulferien_web/controllers/school_controller_test.exs, test/support/factory.ex
=> Updated controller tests by adding period data to them

lib/mehr_schulferien_web/templates/city/show.html.eex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/school/show.html.eex
Part of #245 
Updated addressRegion to use federal_state name.
Updated addressLocality for the federal_state show page to an empty string.
=> Updated addressRegion and addressLocality in events

lib/mehr_schulferien_web/templates/city/show.html.eex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/school/show.html.eex
=> Minor issues

lib/mehr_schulferien/calendars.ex, lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/partial/_federal_state_faq.html.eex, lib/mehr_schulferien_web/views/view_helpers.ex
Related to #267 
This PR adds a question and answer about the next schoolday to the faq. The formatting and translation are NOT finished yet.
=> Added question about next schoolday to faq

lib/mehr_schulferien_web/templates/city/show.html.eex, lib/mehr_schulferien_web/views/view_helpers.ex
=> Fixes missing postalCode bug in city event

.github/workflows/elixir-ci.yml, mix.exs
Elixir version from 1.9 to 1.10
=> Updated Elixir version to 1.10

config/config.exs, lib/mehr_schulferien_web/auth/user_messages.ex, lib/mehr_schulferien_web/controllers/authorize.ex, lib/mehr_schulferien_web/controllers/city_controller.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/controllers/school_controller.ex, lib/mehr_schulferien_web/controllers/user_controller.ex, lib/mehr_schulferien_web/templates/session/new.html.eex, test/mehr_schulferien_web/controllers/city_controller_test.exs, test/mehr_schulferien_web/controllers/confirm_controller_test.exs, test/mehr_schulferien_web/controllers/federal_state_controller_test.exs, test/mehr_schulferien_web/controllers/password_reset_controller_test.exs, test/mehr_schulferien_web/controllers/school_controller_test.exs, test/mehr_schulferien_web/controllers/session_controller_test.exs, test/mehr_schulferien_web/controllers/user_controller_test.exs, test/support/conn_case.ex
Related to #287 
This PR makes sure that only authenticated users can create new periods.
=> Added authorization for creating new periods

lib/mehr_schulferien/calendars.ex, lib/mehr_schulferien_web/controllers/public_holiday_controller.ex, lib/mehr_schulferien_web/router.ex, lib/mehr_schulferien_web/templates/city/show.html.eex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/partial/_public_holidays_table_for_federal_state.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar_summary.html.eex, lib/mehr_schulferien_web/templates/public_holiday/meta.show_within_federal_state.html.eex, lib/mehr_schulferien_web/templates/public_holiday/show_within_federal_state.html.eex, lib/mehr_schulferien_web/templates/school/show.html.eex, lib/mehr_schulferien_web/views/public_holiday_view.ex, mix.exs
e.g. http://localhost:4000/feiertag/d/bundesland/bremen/ostermontag
=> Adds a show page for each federal state public holiday.

test/mehr_schulferien_web/controllers/city_controller_test.exs, test/mehr_schulferien_web/controllers/federal_state_controller_test.exs, test/mehr_schulferien_web/controllers/school_controller_test.exs, test/support/factory.ex
=> Fixed tests for federal_state, city and school controller show pages

lib/mehr_schulferien_web/controllers/city_controller.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/controllers/school_controller.ex, lib/mehr_schulferien_web/templates/city/form.html.eex, lib/mehr_schulferien_web/templates/city/new.html.eex, lib/mehr_schulferien_web/templates/federal_state/form.html.eex, lib/mehr_schulferien_web/templates/federal_state/new.html.eex, lib/mehr_schulferien_web/templates/period/form.html.eex, lib/mehr_schulferien_web/templates/school/form.html.eex, lib/mehr_schulferien_web/templates/school/new.html.eex
=> Removed email address from new_period form

lib/mehr_schulferien/locations.ex, test/mehr_schulferien/locations_test.exs
=> Updated Locations.list_cities_of_country function

lib/mehr_schulferien_web/templates/city/show.html.eex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/federal_state/show_holiday_or_vacation_type.html.eex, lib/mehr_schulferien_web/templates/partial/_one_year_periods_table.html.eex, lib/mehr_schulferien_web/templates/partial/_public_holidays_table_for_federal_state.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar_summary.html.eex, lib/mehr_schulferien_web/templates/public_holiday/show_within_federal_state.html.eex, lib/mehr_schulferien_web/templates/school/show.html.eex, lib/mehr_schulferien_web/views/faq_view_helpers.ex, priv/repo/seeds-public-holidays.exs, priv/repo/seeds.exs
=> Fixed seeds bug

lib/mehr_schulferien_web/views/view_helpers.ex
=> Updated filter in next_schoolday function to include dates that end today

lib/mehr_schulferien/calendars.ex, lib/mehr_schulferien/exceptions.ex, lib/mehr_schulferien/locations.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/controllers/sitemap_controller.ex, lib/mehr_schulferien_web/templates/sitemap/index.xml.eex
=> Updated sitemap to only show holiday_or_vacation_types that a location has

lib/mehr_schulferien/locations.ex, lib/mehr_schulferien_web/templates/federal_state/meta.schulbeginn.html.eex, lib/mehr_schulferien_web/templates/federal_state/schulbeginn.html.eex, lib/mehr_schulferien_web/templates/partial/_federal_state_faq.html.eex, test/mehr_schulferien/locations_test.exs
=> Fix internal links and list_schools_of_country function

lib/mehr_schulferien/calendars.ex, lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/controllers/api/v2/period_controller.ex, lib/mehr_schulferien_web/controllers/controller_helpers.ex, lib/mehr_schulferien_web/templates/city/show.html.eex, lib/mehr_schulferien_web/templates/federal_state/schulbeginn.html.eex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar_summary.html.eex, lib/mehr_schulferien_web/templates/school/show.html.eex, test/mehr_schulferien/periods_test.exs
=> Refactor period data fetching

lib/mehr_schulferien_web/router.ex
=> Changed route for Germany

assets/package-lock.json, lib/mehr_schulferien/calendars.ex, lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/controllers/controller_helpers.ex, lib/mehr_schulferien_web/templates/federal_state/schulbeginn.html.eex, lib/mehr_schulferien_web/templates/federal_state/show.html.eex, lib/mehr_schulferien_web/templates/partial/_federal_state_faq.html.eex, lib/mehr_schulferien_web/templates/partial/_school_start_faq.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar.html.eex, lib/mehr_schulferien_web/views/faq_view_helpers.ex, lib/mehr_schulferien_web/views/view_helpers.ex
=> Refactored federal_state faq to use existing data as much as possible

lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/templates/partial/_three_year_periods_table.html.eex, lib/mehr_schulferien_web/views/period_view.ex, lib/mehr_schulferien_web/views/view_helpers.ex, test/mehr_schulferien/periods_test.exs
=> Swapped the x and y axes for the three_year_periods table

lib/mehr_schulferien/locations.ex, lib/mehr_schulferien_web/controllers/sitemap_controller.ex, lib/mehr_schulferien_web/templates/sitemap/index.xml.eex
=> Updated sitemap

lib/mehr_schulferien/calendars.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex
=> Fixed kategorie bug by adding a search for previous periods if no future periods are found

config/test.exs, lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/templates/partial/_federal_state_faq.html.eex, lib/mehr_schulferien_web/views/faq_view_helpers.ex
=> Added FAQ entry for schulfrei location_name + year

lib/mehr_schulferien_web/controllers/page_controller.ex, lib/mehr_schulferien_web/templates/page/index.html.eex, lib/mehr_schulferien_web/templates/partial/_current_calendar.html.eex, test/mehr_schulferien_web/controllers/page_controller_test.exs
=> Updated page_controller to be able to display multiple countries

lib/mehr_schulferien_web/controllers/country_controller.ex, lib/mehr_schulferien_web/templates/country/show.html.eex, lib/mehr_schulferien_web/templates/partial/_country_periods_table.html.eex, lib/mehr_schulferien_web/templates/partial/_current_calendar.html.eex, lib/mehr_schulferien_web/views/view_helpers.ex
=> Added general overview of year periods to country route

lib/mehr_schulferien_web/controllers/city_controller.ex, lib/mehr_schulferien_web/controllers/controller_helpers.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/controllers/school_controller.ex, lib/mehr_schulferien_web/templates/federal_state/schulbeginn.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar.html.eex
=> Added a calendar below school start FAQ

lib/mehr_schulferien/locations.ex, lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/controllers/sitemap_controller.ex, lib/mehr_schulferien_web/templates/partial/_federal_state_faq.html.eex, lib/mehr_schulferien_web/templates/sitemap/index.xml.eex, test/mehr_schulferien/periods_test.exs
=> Added lastmod for cities and schools to the sitemap and fixed the space bug in the FAQ template

lib/mehr_schulferien_web/templates/partial/_federal_state_faq.html.eex
=> Fixed json bug in federal_state FAQ

lib/mehr_schulferien/calendars/bridge_day_period.ex, lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/controllers/bridge_day_controller.ex, lib/mehr_schulferien_web/router.ex, lib/mehr_schulferien_web/templates/bridge_day/meta.show_within_federal_state.html.eex, lib/mehr_schulferien_web/templates/bridge_day/show_within_federal_state.html.eex, lib/mehr_schulferien_web/templates/partial/_bridge_day_panel.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar.html.eex, lib/mehr_schulferien_web/templates/partial/_vacation_calendar_summary.html.eex, lib/mehr_schulferien_web/views/bridge_day_view.ex
Starts work on #278 
This only adds bridge days for federal states - and the bridge days are for one calendar year (starting Jan 1).
=> Added bridge days route for federal states

lib/mehr_schulferien/exceptions.ex, lib/mehr_schulferien_web/controllers/bridge_day_controller.ex, lib/mehr_schulferien_web/router.ex, lib/mehr_schulferien_web/templates/bridge_day/index_within_federal_state.html.eex, lib/mehr_schulferien_web/templates/bridge_day/meta.index_within_federal_state.html.eex, lib/mehr_schulferien_web/templates/bridge_day/meta.show_within_federal_state.html.eex, lib/mehr_schulferien_web/templates/bridge_day/show_within_federal_state.html.eex, lib/mehr_schulferien_web/templates/partial/_bridge_day_panel.html.eex, test/mehr_schulferien_web/controllers/bridge_day_controller_test.exs
=> Updated bridge days implementation for federal states

lib/mehr_schulferien_web/templates/partial/_bridge_day_panel.html.eex
=> Fixed bug in bridge day panel

lib/mehr_schulferien/exceptions.ex, lib/mehr_schulferien_web/controllers/federal_state_controller.ex, lib/mehr_schulferien_web/controllers/school_controller.ex, test/mehr_schulferien_web/controllers/federal_state_controller_test.exs, test/mehr_schulferien_web/controllers/school_controller_test.exs
=> Added 404 for modus query_param and redirect for additional_categories query_param

lib/mehr_schulferien_web/templates/bridge_day/index_within_federal_state.html.eex, lib/mehr_schulferien_web/templates/bridge_day/show_within_federal_state.html.eex, lib/mehr_schulferien_web/templates/partial/_bridge_day_panel.html.eex, lib/mehr_schulferien_web/templates/sitemap/index.xml.eex
=> Added event schema for bridge days and added bridge day urls to sitemap

lib/mehr_schulferien/periods.ex, lib/mehr_schulferien_web/controllers/bridge_day_controller.ex, test/mehr_schulferien/periods_test.exs
This fixes a failing test in periods_test.exs.
=> Fixed bug in periods_test

lib/mehr_schulferien_web/templates/partial/_current_calendar.html.eex, lib/mehr_schulferien_web/views/page_view.ex
Related to #472 and fixes #517 
This PR also fixes the issue where weekends and public holidays were being displayed in the wrong places.
=> Fixes bugs in root page table

lib/mehr_schulferien_web/templates/partial/_federal_state_faq.html.eex
=> Fixed federal_state_faq bug

lib/mehr_schulferien_web/templates/federal_state/show_holiday_or_vacation_type.html.eex
=> Updated mini-calendar in show_holiday_or_vacation_type page

assets/package-lock.json, assets/package.json
=> Updated node packages
